server:
  port: 8081

spring:
  application:
    name: auth-service
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: mySuperSecretKeyForJWTWhichShouldBeVerySecureAndLongEnough123!
  expiration: 86400000 # 1 día en milisegundos
